# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    csrf_protection: true
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null 
        cookie_secure: auto
        #cookie_samesite: lax
        #storage_id: session.storage.native
        cookie_lifetime: 36000000


#php bin/console config:dump-reference framework
    # Note that the session will be started ONLY if you read or write from it.
    #session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            handler_id: null
            storage_factory_id: session.storage.factory.mock_file
            cookie_secure: auto

#cookie_lifetime
#type: integer
#This determines the lifetime of the session - in seconds. Setting this value to 0 means the cookie is valid for the length of the browser session.
